- README.md
Provide attribution to Eclipse Foundation.
> Refer to OpenJ9 as Eclipse OpenJ9 in comments and text.

- 8/jdk/alpine/Dockerfile.hotspot
- 8/jdk/alpine/Dockerfile.openj9
- 8/jdk/ubuntu/Dockerfile.hotspot
- 8/jdk/ubuntu/Dockerfile.openj9
- 9/jdk/alpine/Dockerfile.hotspot
- 9/jdk/alpine/Dockerfile.openj9
- 9/jdk/ubuntu/Dockerfile.hotspot
- 9/jdk/ubuntu/Dockerfile.openj9
- build_latest.sh
- common_functions.sh
- generate_latest_sums.sh
- generate_manifest_script.sh
- update_multiarch.sh
This also makes sure that ppc64le openj9 should get picked up automatically when it becomes available.
> Add proper aarch64/arm64 support across all scripts.

- build_latest.sh
- common_functions.sh
Fix build_latest.sh to build VMs (Hotspot/Openj9) only on supported arches as before.
> Fix for building VMs only on supported arches.

- generate_latest_sums.sh
- slim-java.sh
- update_multiarch.sh
1. Fix aarch docker image (pick latest tarball for multiple builds).
2. Fix PATH for all builds.
3. Update the slim-build.sh to the correct one !
> aarch + PATH + slim-build.sh fixes

- update_multiarch.sh
Enable container support by default in both Hotspot and OpenJ9.
Also enable idle optimizations in OpenJ9.
> Enable container support

- update_multiarch.sh
To prevent any non-OpenJ9 build of OpenJDK throwing up errors due to the
new container exploitation options added to the OpenJ9 docker images,
we can add -XX:+IgnoreUnrecognizedVMOptions to ignore these OpenJ9-specific
options.
Signed-off-by: Mark Stoodley <mstoodle@ca.ibm.com>
> Add -XX:+IgnoreUnrecognizedVMOptions to OpenJ9 options

- test_multiarch.sh
Jenkins jobs dont have a tty attached and so all docker test jobs fail.
> Remove "-it" flag from the docker run for the tests.

- update_multiarch.sh
The sha256sum check fails sometimes even though the sum in the
Dockerfile matches the computed sum. This *could* be due to the
downloaded file not in sync with the fs. Adding a delay in doing the
check seems to make the error go away.
Signed-off-by: Dinakar Guniguntala Dinakar.G@in.ibm.com
> Fix occasional sha256sum failures.

- dockerfile_functions.sh
Ubuntu 18.04 is about 30 MB smaller than 16.04. Will switch over to 18.04 in the long term, currently only for nightly and slim builds for feedback and testing.
> Use Ubuntu 18.04 for nightly and slim builds.

- common_functions.sh
This PR is dependent on API PR [#70](https://github.com/AdoptOpenJDK/openjdk-api/pull/70)
> Change openjdkImpl to openjdk_impl to match the change in v2 api.

- config/slim-java_bin_del.list
- config/slim-java_lib_del.list
- dockerfile_functions.sh
- slim-java.sh
* Remove several tools that are not needed for a slim build. The tools to be removed are now maintained in config/slim-java_bin_del.list
* Dont optimize charsets.jar as both OpenJ9/Hotspot need an updated sun/nio/cs/ext/ExtendedCharsets.class that checks for a excludes file for charsets that need to be ignored.
* Remove tools.jar and ct.sym from jre/lib
* Since ct.sym is now to be removed, no need to optimize it.
> Slim updates

- dockerfile_functions.sh
HOW I VERIFIED: 
Manually copy paste change in existing alpine dockerfile + docker build + docker run -it + java -version + compiled and executed sample java program
COMMENTS
Didn't move those to /usr/glibc-compat, please **verify** if it's fine.
- zlib is installed by default in /lib/libz*
- apk add libgcc -> /lib/usr/libgcc*
- apk add libstdc++ -> lib/usr/libstdc++
Need to deploy new images + automatic tests ?
>  alpine: verified download + fixed version for zlib, gcc-libs and glibc

- config/hotspot.config
- config/openj9.config
Since we are not generating builds for these versions anymore, no need to build docker images either. Ideally we want people to be using only the 8 and 11 docker images. Note that this also means that the version 9 and 10 docker images will no longer be updated for OS vulnerabilities. Let me know if there are any objections to this.
> Do not build docker images for versions 9 and 10 anymore.

- build_latest.sh
- dockerfile_functions.sh
JDK has both "jre/bin" and "bin" whereas, JRE has only "bin" dir. We only need the "bin" path in both cases.
> Handle both JRE and JDK dir structures gracefully to generate the JRE path.

- common_functions.sh
- generate_latest_sums.sh
- generate_manifest_script.sh
- test_multiarch.sh
PR #101 added support for the base JRE tags. This PR adds support for the manifest entries for multi arch and updates the test scripts to test the JRE images as well.
> Update manifest and test scripts to support the JRE tags.

- 10/jdk/alpine/Dockerfile.hotspot.nightly.full
- 10/jdk/alpine/Dockerfile.hotspot.nightly.slim
- 10/jdk/alpine/Dockerfile.hotspot.releases.full
- 10/jdk/alpine/Dockerfile.hotspot.releases.slim
- 10/jdk/ubuntu/Dockerfile.hotspot.nightly.full
- 10/jdk/ubuntu/Dockerfile.hotspot.nightly.slim
- 10/jdk/ubuntu/Dockerfile.hotspot.releases.full
- 10/jdk/ubuntu/Dockerfile.hotspot.releases.slim
- 11/jdk/alpine/Dockerfile.hotspot.nightly.full
- 11/jdk/alpine/Dockerfile.hotspot.nightly.slim
- 11/jdk/alpine/Dockerfile.hotspot.releases.full
- 11/jdk/alpine/Dockerfile.hotspot.releases.slim
- 11/jdk/ubuntu/Dockerfile.hotspot.nightly.full
- 11/jdk/ubuntu/Dockerfile.hotspot.nightly.slim
- 11/jdk/ubuntu/Dockerfile.hotspot.releases.full
- 11/jdk/ubuntu/Dockerfile.hotspot.releases.slim
- 8/jdk/alpine/Dockerfile.hotspot.nightly.full
- 8/jdk/alpine/Dockerfile.hotspot.nightly.slim
- 8/jdk/alpine/Dockerfile.hotspot.releases.full
- 8/jdk/alpine/Dockerfile.hotspot.releases.slim
- 8/jdk/ubuntu/Dockerfile.hotspot.nightly.full
- 8/jdk/ubuntu/Dockerfile.hotspot.nightly.slim
- 8/jdk/ubuntu/Dockerfile.hotspot.releases.full
- 8/jdk/ubuntu/Dockerfile.hotspot.releases.slim
- dockerfile_functions.sh
For https://github.com/AdoptOpenJDK/openjdk-docker/issues/79
> Closes AdoptOpenJDK/openjdk-docker/issues#79 - Switch JAVA_TOOL_OPTIONS to use new container support flag

- build_latest.sh
- common_functions.sh
- dockerfile_functions.sh
- generate_manifest_script.sh
- test_multiarch.sh
1. User "docker build --pull" to ensure we always get the latest images.
2. Replce the "+" in the versions with "_" instead of "."
3. Change "apk --update add" to "apk add" as --update is redundant.
4. Dont print an empty "JAVA_TOOL_OPTIONS"
5. Change "check_image" to return "docker pull" return code so that the
caller can decide what needs to be done with it.
6. Only create manifest entries for arches that have builds for the
current build in question.
> Fix minor issues to ready for official images.

- common_functions.sh
- update_all.sh
- update_multiarch.sh
If a shasum file is missing handle gracefully.
@gdams has already fixed update_multiarch.sh to generate version specific Dockerfiles, this adds a superscript to generate for all versions.
Fixes #143.
> Add script to create Dockerfiles for all supported versions.

- dockerfile_functions.sh
Based on https://github.com/frol/docker-alpine-glibc/blob/master/Dockerfile
Generated dockerfile 
```
#
#
#
#
#
FROM alpine:3.9
LABEL maintainer="dinakar.g@in.ibm.com"
ENV JAVA_VERSION jdk8u212-b03
ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en' LC_ALL='en_US.UTF-8'
RUN apk add --no-cache --virtual .build-deps curl binutils \
&& GLIBC_VER="2.29-r0" \
&& ALPINE_GLIBC_REPO="https://github.com/sgerrand/alpine-pkg-glibc/releases/download" \
&& GCC_LIBS_URL="https://archive.archlinux.org/packages/g/gcc-libs/gcc-libs-8.2.1%2B20180831-1-x86_64.pkg.tar.xz" \
&& GCC_LIBS_SHA256=e4b39fb1f5957c5aab5c2ce0c46e03d30426f3b94b9992b009d417ff2d56af4d \
&& ZLIB_URL="https://archive.archlinux.org/packages/z/zlib/zlib-1%3A1.2.11-3-x86_64.pkg.tar.xz" \
&& ZLIB_SHA256=17aede0b9f8baa789c5aa3f358fbf8c68a5f1228c5e6cba1a …
```
> fix: #105 - Set locale in alpine image

- 10/jdk/alpine/slim-java.sh
- 10/jdk/ubuntu/slim-java.sh
- 11/jdk/alpine/slim-java.sh
- 11/jdk/ubuntu/slim-java.sh
- 8/jdk/alpine/slim-java.sh
- 8/jdk/ubuntu/slim-java.sh
- 9/jdk/alpine/slim-java.sh
- 9/jdk/ubuntu/slim-java.sh
- build_all.sh
- build_latest.sh
- common_functions.sh
- dockerfile_functions.sh
- generate_latest_sums.sh
- generate_manifest_script.sh
- slim-java.sh
- test_all.sh
- test_multiarch.sh
- update_manifest_all.sh
- update_multiarch.sh
macOS ships with an old version of bash that doesn't recognise `declare -A`. Using `/usr/bin/env bash` instead of referencing `/bin/bash` directly allows macOS users to use homebrew supplied bash instead of the built-in one.
> Use `#!/usr/bin/env bash` instead of `#!/bin/bash`

- common_functions.sh
- dockerfile_functions.sh
- generate_manifest_script.sh
1. manifest build is currently broken as the OS and the distro cannot be used interchangeably. Using "os" and "os_family" to indicate "distro" and "generic OS" respectively to reduce code changes.
2. Remove maintainer LABEL, no longer a standard practice for docker images.
3. Have jshell as default CMD only for jdk builds and not jre ones.
4. Add arm64 manifest entries for aarch64.
5. Added back spaces in the Dockerfiles between statements to keep it readable.
> Fix broken manifest build and other minor changes

- 11/jdk/windows/Dockerfile.hotspot.nightly.full
- 11/jdk/windows/Dockerfile.hotspot.releases.full
- 11/jdk/windows/Dockerfile.openj9.nightly.full
- 11/jdk/windows/Dockerfile.openj9.releases.full
- 12/jdk/windows/Dockerfile.hotspot.nightly.full
- 12/jdk/windows/Dockerfile.hotspot.releases.full
- 12/jdk/windows/Dockerfile.openj9.releases.full
- 8/jdk/windows/Dockerfile.hotspot.nightly.full
- 8/jdk/windows/Dockerfile.hotspot.releases.full
- 8/jdk/windows/Dockerfile.openj9.nightly.full
- 8/jdk/windows/Dockerfile.openj9.releases.full
- dockerfile_functions.sh
Addresses some nits raised in https://github.com/docker-library/official-images/pull/6116
> minor refactor of windows dockerfiles

- dockerfile_functions.sh
Move from gcc libs 8.2.1-B20180831-1 to 9.1.0-2 version.
> Update the alpine gcc libs package to the latest one as the older one is now deprecated.

- common_functions.sh
- dockerfile_functions.sh
1. Use downloaded shasums in the current loop instead of downloading it for every VM/Version/Package/Build combintion.
2. Sort the generated shasums per arch in the Dockerfile so as to not generate spurious diffs.
> Speed up the Dockerfile generation process

- 11/jre/alpine/Dockerfile.hotspot.releases.full
- dockerfile_functions.sh
Resolves: `DKL-DI-0004: Use apk add with --no-cache` which results in a FATAL error for any container that extends the Alpine image.
> Resolved Dockle: Use apk add with --no-cache

- common_functions.sh
- config/tags.config
Add default as Linux os for v2 query if no arch specified.
Add comments on error exit.
> Remove redundant jre suffix tags as they are already part of version.

- README.md
- common_functions.sh
- config/hotspot.config
- config/openj9.config
- config/tags.config
- dockerfile_functions.sh
This PR adds support to the RedHat [UBI](https://www.redhat.com/en/blog/introducing-red-hat-universal-base-image) image. UBI Has three variants (ubi, ubi-minimal and ubi-init). This PR only adds support for ubi-minimal and for version 8.
Fixes #162
> Add support for RedHat ubi-minimal OS.

- common_functions.sh
- config/hotspot.config
- config/openj9.config
- dockerhub_doc_config_update.sh
Stop building Java 12 as well.
> Add support for building Java 13 docker images.

- .travis.yml
- build_all.sh
- build_latest.sh
- common_functions.sh
- generate_manifest_script.sh
- test_all.sh
- test_multiarch.sh
- update_manifest_all.sh
Reduce the inner loops, so that we can do cleanup in the outer loops. This helps to reduce disk ballooning during builds.
> Have smaller loops while building / creating manifests / testing docker images.

- build_latest.sh
- common_functions.sh
- config/hotspot-official.config
- config/hotspot.config
- dockerfile_functions.sh
This enables building nanoserver images. This bases the images on the powershell core nanoserver image so that pwsh is available. This requires 8u232 for jdk8 based images and 11.0.5 for jdk11 based images (otherwise there are missing dlls in the nanoserver images). There are no nanoserver images for 2016, so it is not included.
> Enable nanoserver images for hotspot

- dockerfile_functions.sh
Example dockerfile 
```dockerfile
#
#
#
#
#
FROM debian:buster
ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en' LC_ALL='en_US.UTF-8'
RUN apt-get update \
&& apt-get install -y --no-install-recommends curl ca-certificates locales \
&& echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen \
&& locale-gen en_US.UTF-8 \
&& rm -rf /var/lib/apt/lists/*
ENV JAVA_VERSION jdk8u
RUN set -eux; \
ARCH="$(dpkg --print-architecture)"; \
case "${ARCH}" in \
aarch64|arm64) \
ESUM='ab6a696a51a14546dc0d0cdbf9e53c5bd311364daa7271ae1c5938e562152294'; \
BINARY_URL='https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u-2019-08-20-11-35/OpenJDK8U-jre_aarch64_linux_hotspot_2019-08-20-11-35.tar.gz'; \
;; \
armhf) \
ESUM='0ab47f0effd9e6b18693dac24cb6b5fc00ce16e57bda8c859238f2f9f595c1a5'; \ …
```
> feat: Update debian to 'buster'

- dockerfile_functions.sh
Ensure the UBI base image version does not change without explicit update in the generation scripts.
> Use explicit UBI version rather than latest.

- common_functions.sh
- dockerfile_functions.sh
Use the v3 API
CentOS uses armv7l instead of armhf
Alpine glibc latest is now 2.30-r0
Fixes #279
> Jenkins build fixes

- common_functions.sh
- dockerfile_functions.sh
v3 API does not do return JSON in pretty print format. This adds a new dependency on python to be able to parse data returned. Need to ensure all machines tagged with `docker` have python installed and working. Need to test v3 API on some docker corner cases.
Temporarily disabling v3 API usage until these issues are sorted out.
> Temporarily fallback to the v2 API until v3 usage is sorted out.

- common_functions.sh
After running manifest job, multiple tags exist for the same image and they are not getting cleaned up after the run.
Also remove any dangling containers from previous runs.
> Cleanup images with multiple tags.

- common_functions.sh
before calling image prune to ensure that we remove all dangling images.
> During cleanup, remove the adopt images first

- .gitignore
- build_all.sh
- build_latest.sh
- common_functions.sh
- test_all.sh
- update_all.sh
- update_manifest_all.sh
This should help speed up the jenkins docker build job considerably. This should also ensure that we do not rebuild images unnecessarily. Fixes #307. Also #302 was created to resolve the same underlying problem, but should become less of an issue with this.
> Add checks to rebuild docker images only if needed.

- build_latest.sh
- common_functions.sh
Note that this puts a dependency on Ubuntu 16.04 as python3 is the default only on Ubuntu.
> Move back to python3 due to infrastructure issues.

- build_latest.sh
Checking for build timestamps of base OS docker image to determine if a rebuild of the corresponding Adopt Image is needed, is flaky, as a delay in Adopt build jobs might cause an OS update to be missed. Instead checking the individual shasums of each of the base OS Image layers being present in the Adopt image ensures that any update to the base OS Image will trigger a rebuild of the Adopt Image.
> Make the base OS image update check more robust

- config/hotspot-official.config
- config/hotspot.config
`armv7l` entries for Hotspot 8 were originally not added as the builds were not available. Subsequently the builds were made available but the corresponding docker entries were not added.
Fixes #341
> Add missing armv7l entries for Hotspot version 8.

- 10/jdk/alpine/Dockerfile.hotspot.nightly.full
- 10/jdk/alpine/Dockerfile.hotspot.nightly.slim
- 10/jdk/alpine/Dockerfile.hotspot.releases.full
- 10/jdk/alpine/Dockerfile.hotspot.releases.slim
- 10/jdk/alpine/Dockerfile.openj9.nightly.full
- 10/jdk/alpine/Dockerfile.openj9.nightly.slim
- 10/jdk/alpine/Dockerfile.openj9.releases.full
- 10/jdk/alpine/Dockerfile.openj9.releases.slim
- 9/jdk/alpine/Dockerfile.hotspot.nightly.full
- 9/jdk/alpine/Dockerfile.hotspot.nightly.slim
- 9/jdk/alpine/Dockerfile.hotspot.releases.full
- 9/jdk/alpine/Dockerfile.hotspot.releases.slim
- 9/jdk/alpine/Dockerfile.openj9.nightly.full
- 9/jdk/alpine/Dockerfile.openj9.nightly.slim
- 9/jdk/alpine/Dockerfile.openj9.releases.full
- 9/jdk/alpine/Dockerfile.openj9.releases.slim
- README.md
Versionbump 9/10 alpine dockerfiles from v3.8 -> v3.12 (latest) and update README.md
> Bump alpine version to v3.12 (latest)

- dockerfile_functions.sh
This PR updates the dockerfile_functions.sh to use GCC 10.1
for alpine based images, as @consult-kk mentioned, to fix CVE-2019-15847.
Fixes #336
> openjdk-docker/dockerfile_functions.sh: Alpine bump GCC to 10.1

- dockerfile_functions.sh
The gcc-libs tarball is not cleaned up properly in /tmp and is increasing the size of all Alpine images by 181MB
> Cleanup gcc-libs tarfile

- dockerfile_functions.sh
- generate_openj9_scc.sh
As SCC (shared class cache) makes java startup faster we are now generating the SCC as part of build process and ship OpenJDK OpenJ9 images with SCC in it. (As OpenJ9 images are used in cloud context and mostly for springboot the cache generated contains tomcat classes as well)
FYI @dinogun , Please lemme know your views on it 
> Added SCC script which generate SCC at image build

- build_latest.sh
- generate_openj9_scc.sh
Fixes the issue mentioned in the [PR comment](https://github.com/AdoptOpenJDK/openjdk-docker/pull/338#issuecomment-688405369)
- Copying `generate_openj9_scc.sh` to the dockerfile location to make it available in docker build context (Thanks @mpirvu for raising this)
- Added a check for downloading artifacts to skip extracting and running them in case of broken links
@dinogun can you please review this ?
> Fixes failure over missing file in docker context

- 13/jdk/windows/nanoserver-1809/Dockerfile.hotspot.nightly.full
- 13/jdk/windows/nanoserver-1809/Dockerfile.hotspot.releases.full
- 13/jre/windows/nanoserver-1809/Dockerfile.hotspot.nightly.full
- 13/jre/windows/nanoserver-1809/Dockerfile.hotspot.releases.full
- 14/jdk/windows/nanoserver-1809/Dockerfile.hotspot.nightly.full
- 14/jdk/windows/nanoserver-1809/Dockerfile.hotspot.nightly.slim
- 14/jdk/windows/nanoserver-1809/Dockerfile.openj9.nightly.full
- 14/jdk/windows/nanoserver-1809/Dockerfile.openj9.nightly.slim
- 14/jdk/windows/nanoserver-1909/Dockerfile.hotspot.nightly.full
- 14/jdk/windows/nanoserver-1909/Dockerfile.hotspot.nightly.slim
- 14/jdk/windows/nanoserver-1909/Dockerfile.openj9.nightly.full
- 14/jdk/windows/nanoserver-1909/Dockerfile.openj9.nightly.slim
- 14/jre/windows/nanoserver-1809/Dockerfile.hotspot.nightly.full
- 14/jre/windows/nanoserver-1809/Dockerfile.hotspot.nightly.slim
- 14/jre/windows/nanoserver-1809/Dockerfile.openj9.nightly.full
- 14/jre/windows/nanoserver-1809/Dockerfile.openj9.nightly.slim
- 14/jre/windows/nanoserver-1909/Dockerfile.hotspot.nightly.full
- 14/jre/windows/nanoserver-1909/Dockerfile.hotspot.nightly.slim
- 14/jre/windows/nanoserver-1909/Dockerfile.openj9.nightly.full
- 14/jre/windows/nanoserver-1909/Dockerfile.openj9.nightly.slim
- 8/jdk/windows/nanoserver-1809/Dockerfile.hotspot.releases.slim
- 8/jdk/windows/nanoserver-1809/Dockerfile.openj9.releases.full
- 8/jdk/windows/nanoserver-1809/Dockerfile.openj9.releases.slim
- 8/jre/windows/nanoserver-1809/Dockerfile.hotspot.releases.slim
- 8/jre/windows/nanoserver-1809/Dockerfile.openj9.releases.full
- 8/jre/windows/nanoserver-1809/Dockerfile.openj9.releases.slim
This is causing official image build failures as in this [PR](https://github.com/docker-library/official-images/pull/8781/checks?check_run_id=1173414530).
> Remove the use of unsupported powershell based images in older dockerfiles.

- generate_openj9_scc.sh
As @mpirvu pointed in #404 the generated shared class cache is inaccessible for non-root users. This PR fixes it by updating the file permissions.
@dinogun Can i please get your review ?
> Fixs issue 404 - Makes scc accessible to non-root user

- dockerfile_functions.sh
As pointed by @mpirvu in #403 OpenJ9 has container support turned on [by this patch](https://github.com/eclipse/openj9/pull/3184) So its no longer needed to added in the java tool options. 
@dinogun Can i please have it reviewed ?
> Fixs issue 403 - Removing default options from JAVA_TOOL_OPTIONS

- generate_openj9_scc.sh
PR #407 makes the cache readable to non-root users
while this change gives write access to non-root users
For discussion details : https://github.com/AdoptOpenJDK/openjdk-docker/pull/407#pullrequestreview-498417175
@karianna @dinogun can i have your review ?
> Changing scc directory permission to 777

- dockerfile_functions.sh
Supercedes #426 
Fixes #424 
Instead of modifying the `generate_openj9_scc.sh` script to run under Dash instead make it so that bash is present for running the script on Alpine images and then removed afterwards.
> Make sure bash and curl are present before running the generate_openj9_scc.sh script on Alpine images

- .github/workflows/continuous-integration-workflow.yml
This matches the supported version in `common_functions.sh`. Alas, it doesn't appear that Github Actions support Alpine as a runner so I guess that idea is off the table.
> Add JDK 15 to Github Actions matrix

- dockerfile_functions.sh
Based on [reviews](https://github.com/docker-library/official-images/pull/8781#issuecomment-701052303) at docker official images moving the scc generation part from script to the dockerfile itself.
@karianna @dinogun Can i have your views on this ? Thanks in advance.
> Add SCC generation code to the dockerfile and remove the external script

- dockerfile_functions.sh
Adds a comment in the dockerfile describing the steps which 
are executed in the RUN command along with description of
how the SCC generated can be used as base cache layer for
applications which add their cache on top of it.
Also adds a better line spacing and sets the shell back to `sh`
@karianna  @dinogun Can i please have your views on this ? 
Thanks in advance !
> Adds comment, sets shell back to sh, better linespacing for readability

- dockerfile_functions.sh
The PR comment in docker official images state the use of semicolon based script rather than a script with logical and (&&)
REF: https://github.com/docker-library/official-images/pull/8781#issuecomment-708648503
This PR makes the script to have semicolon.
@dinogun Can i know your views on this ? Thanks in advance.
> Moving from logical end (&&) to semicolon based script

- dockerfile_functions.sh
> Rollback ubuntu version to `bionic` (18.04) to fix the official image tags.

- dockerfile_functions.sh
- dockerhub_doc_config_update.sh
ubuntu dockerhub tags should now refer to focal.
> Move to Ubuntu 20.04 (focal) as base image

- .appveyor.yml
- .github/workflows/continuous-integration-workflow.yml
- .travis.yml
- build_all.sh
- build_latest.sh
- common_functions.sh
The flag `runtype` can be set either to build or test
If its set to test the dockerimages are only built for
ubuntu, alpine and ubi if the script is running on a
x86_64 Linux machine to build OpenJ9 images.
The github workflows are using `build_latest.sh` script
to generate the docker images on each PR. Recent changes
to OpenJ9 docker images added the SCC generation feature
to it which is taking up quite a bit of time to build the
docker images.
Fixes #452 
@karianna @dinogun  Can i get your views on this to proceed with the PR ?
> Adding a flag 'runtype'  to set the oses for PR build

- dockerfile_functions.sh
#471 states that current version (8.2) of UBI has vulnerability issues. Updating the version from 8.2 to 8.3
Fixes #471 
@dinogun Can i have your views on this ? Thanks in advance.
> Updates UBI images to version 8.3

- dockerfile_functions.sh
As mentioned here https://github.com/AdoptOpenJDK/openjdk-docker/issues/464#issuecomment-730983567 the tomcat startup issue is seen in past few builds, Figured out that the earlier tomcat runs are not cleared with shutdown script properly, So manually killing the tomcat process.
> Use kill instead of shutdown script to avoid tomcat startup issue

- dockerfile_functions.sh
#402 states that user might override the scc settings when he sets the ENV var `OPENJ9_JAVA_OPTIONS`. Ideally the user should be aware that he was overriding the ENV set by base image and add on top that but for a better user experience this PR adds the `-Xshareclasses` option to `JAVA_TOOL_OPTIONS` which is already being set.
@dinogun @karianna Can i have your views on this ?
PS: This PR is currently work in progress as this might not turn as the perfect solution for the problem stated in #402 . Raising this PR to make incremental changes based on the discussion happening in this thread. 
> -Xshareclasses option added to JAVA_TOOL_OPTIONS

- dockerfile_functions.sh
UBI images are not shipped with `ps` utility which we use for generating SCC in OpenJ9 images. So adding and removing the package `procps` in UBI images
@dinogun @karianna Can i have your views on this ?
> Added procps package to run the SCC script in UBI

- dockerfile_functions.sh
Debian images are not shipped with ps utility which we use for generating SCC in OpenJ9 images. So adding and removing the package procps in debian images
@dinogun @karianna Can i have your views on this ?
> Added ps installation in debian to generate SCC

- build_latest.sh
Currently the PR checks are passing even if there are some docker images getting failed, So failing the builds on an error at a PR stage gives us an advantage to verify if there are any failure before hand than finding them at nightly build failures.
Note: This PR is currently work in progress as changes might be needed to fit the data collection part for summary table. Will raise another PR for summary table by making changes on top of this. Once summary table part is fixed will remove the WIP tag
> WIP: Exiting the build in PR check on a failure

- build_all.sh
- build_latest.sh
- common_functions.sh
Earlier the path was incorrect and as a result the jenkins job log was missing the summary table. The file is now created at the root dir (i.e openjdk-docker) and will be updated by the `build_image` function to log the docker build status. In the end the table is displayed and the temporary file `.summary_table` is deleted.
@dinogun Can i please have it reviewed ? Thanks in advance.  
> Fixed path issue for summary table

- build_all.sh
- build_latest.sh
- snyk.sh
> chore: Add snyk docker scanning feature

- dockerfile_functions.sh
As we use `-force` option it expects `CATALINA_PID` , Initially kill fails as `CATALINA_PID` is not set but the script shuts down tomcat gracefully. Increased shutdown timer to 15 secs to give a buffer to shutdown.
>  Reverted back to use shutdown.sh for shutting down tomcat gracefully

- build_latest.sh
`build_image` function is called passing only one tag but in function its expected to be an array (multiple tags - not sure about that) so I haven't disturbed the existing mechanism. This PR changes the `tags` variable not to prepend the tag which is resulting in the breakage of adopt image check in dockerhub.
Fixes #507 
> Fixes issue with the tag concatnation

- README.md
- dockerfile_functions.sh
I bump the version of alpine to the latest stable, 3.13: https://www.alpinelinux.org/releases/
> Bump alpine version to v3.13 (latest)

- README.md
- dockerfile_functions.sh
Issue #520 states that there are issues with `alpine 3.13` based on [these comments](https://github.com/AdoptOpenJDK/openjdk-docker/issues/520#issuecomment-787456869) rolling back alpine version to `3.12` till the issues with `alpine 3.13` are investigated. 
> Rolling back alpine version to 3.12 as there are issues with 3.13

- README.md
- common_functions.sh
- config/hotspot.config
- config/openj9.config
- dockerfile_functions.sh
- Adds 20H2 configs and script handling
- Updates Windows gen to use an installer container with powershell
- Fix configs for Windows jre that should not have a slim variant
- Use curl and tar for installation steps (included in Windows)
- The nanoserver based containers are much smaller (>100MB) because of the removal of pwsh from the images
> Add Windows 2019 20H2 configs

- config/hotspot-official.config
- config/hotspot.config
- config/openj9-official.config
- config/openj9.config
This will help distinguish between alpine-linux, linux and windows variants.
Currently alpine-linux is only turned on for hotspot 16-jdk and 16-jre.
> Add "OS_Family" to config files

- README.md
- build_latest.sh
- common_functions.sh
- dockerfile_functions.sh
- generate_manifest_script.sh
- update_multiarch.sh
This uses the native musl java builds for Java 16 and hotspot for x86_64 only. Uses the `alpine-linux` `OS_Family` that was introduced in PR #534 to determine which Java build to use for a given config.
> Add support for musl based native alpine docker images.

- test_multiarch.sh
os family check for shasums was added as part of PR #535
> Add "os family" functionality to the test script.

- dockerfile_functions.sh
#536 states that there are issues with generation of docker images as part of jenkins workflow. From the exploration done by @sxa which is described in the [issue comment](https://github.com/AdoptOpenJDK/openjdk-docker/issues/536#issuecomment-814832348) states that rolling back to 18.04 will avoid the failures due to GPG key error ([sample error](https://github.com/AdoptOpenJDK/openjdk-docker/issues/536#issuecomment-814616515))
This fix rolls back the ubuntu version to 18.04 on `armv7l` architecture.
> Rolling back ubuntu version to 18.04 on armv7l due to GPG error

- Jenkinsfile
As we are seeing [RPC error](https://ci.adoptopenjdk.net/view/Docker%20Images/job/openjdk_build_docker_multiarch/289/consoleText) in JDK 16 docker nightly builds
```
--------------------
23 |     
24 | >>> RUN yum install -y tzdata openssl curl ca-certificates fontconfig gzip tar \
25 | >>>     && yum update -y; yum clean all
26 |     
--------------------
error: failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c yum install -y tzdata openssl curl ca-certificates fontconfig gzip tar     && yum update -y; yum clean all]: exit code: 139
#############################################
ERROR: Docker build of image: -t adoptopenjdk/openjdk16:armv7l-centos-jdk-16_36 from Dockerfile.hotspot.releases.full failed.
#############################################
``` …
> Removing TARGET_ARCHITECTURE to avoid cross platform image build on x64 for armv7l JDK 16

- slim-java.sh
Latest PR #554 PR checks fail as the OpenJ9 slim builds are failing. https://github.com/AdoptOpenJDK/openjdk-docker/pull/554#issuecomment-827680467 states that removing `default` directory is causing the JVM to stop with the error  
```
Selected VM [default] does not exist.
This JVM package includes both the '-Xcompressedrefs' and the '-Xnocompressedrefs' configurations, however the VM directory could not be found. Please download the latest JVM package or build with the most recent changes and run the JVM again.
```
Changes are made to avoid deleting `default` directory (`jre/lib/amd64/default`) in case of OpenJ9
> Avoids trimming Default directory as it's required in OpenJ9

- build_latest.sh
- common_functions.sh
- config/hotspot.config
- config/openj9.config
- dockerfile_functions.sh
- slim-java.ps1
The windows CI jobs weren't running any builds because we skipped releases
> try building windows dockerfiles for releases

- .github/workflows/updater.yml
Adds a weekly cron job that runs the dockerfile updater.
This job will also run whenever something is pushed to master
> add updater github action

- Jenkinsfile
JDK 16 builds are getting [successfully built](https://ci.adoptopenjdk.net/job/openjdk_build_docker_multiarch/307/execution/node/71/log/?consoleFull) after moving from `buildx` environment, So making similar changes to all the JDK versions. 
> Moving to docker build on ARM from buildx (x64) for all JDK versions

- README.md
- dockerfile_functions.sh
Issue #520 states that upgrading alpine version to 3.13 is causing segfaults. Expecting issue is related to glibc libs so updating them to the latest release. There are latest updates for `glibc libs` [link](https://archive.archlinux.org/packages/g/gcc-libs/) and `z libs` [link](https://archive.archlinux.org/packages/z/zlib/) as well. Will be parking this PR as a draft and will be updating it incrementally after investigating the issue and testing the changes. Please kindly provide your views in the review comments to take this fix forward. Thanks.
> Upgrading alpine version to 3.13 with glibc updates

- config/hotspot.config
- config/openj9.config
- dockerfile_functions.sh
@dinogun Fix contains necessary changes requried resolve the slim package issues in ubi and others
This PR Does not contains the multi stage build, whichI indicated in discussion. Would like that to be add in this PR or send as another one. This PR is failrly straight forwrd, Multi stage build requires additional unit testing.
> Missing slim fixes to ubi, ubi-minimal, clefos

- dockerfile_functions.sh
This PR to resolve #565. In addition using `latest` tag removes the need to change/update on every minor version update. Table below indicates that `latest` tag points `ubi8` up to date fixes.
```
$ docker images | grep redhat
registry.access.redhat.com/ubi8/ubi           latest    0724f7c987a7   2 weeks ago     226MB
registry.access.redhat.com/ubi8/ubi           8.4       0724f7c987a7   2 weeks ago     226MB
registry.access.redhat.com/ubi8/ubi           8.3       613e5da7a934   5 weeks ago     205MB
registry.access.redhat.com/ubi8/ubi-minimal   latest    d7cfe75eb0e4   2 weeks ago     103MB
registry.access.redhat.com/ubi8/ubi-minimal   8.4       d7cfe75eb0e4   2 weeks ago     103MB
registry.access.redhat.com/ubi8/ubi-minimal   8.3       332744c1854d   5 weeks ago     103MB …
```
> Fix #565, use latest tag for UBI8

- dockerfile_functions.sh
Fixes #391 
Fix provided by @rhuddleston in https://github.com/AdoptOpenJDK/openjdk-docker/issues/391#issue-687407793
`/UTC` is not an valid timezone, you can check the valid zones [here](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) 
@dinogun  Can i have your views on this ?
> Added DEBIAN_FRONTEND=noninteractive to fix the timezone issue

- Jenkinsfile
- build_all.sh
- common_functions.sh
This will resolve the ever expanding docker cache on some of the machines which is ultimately chewing up all of the disk space in `/var/lib/docker`
Fixes https://github.com/adoptium/infrastructure/issues/3007
(Note that the https://ci.adoptium.net/job/openjdk_build_docker_multiarch/ job is currently set to run from my branch for testing and will need to be switched back after this is merged, as I don't really want it running from the branch!)
> Prune build cache after creating images
