- 10/jdk/alpine/Dockerfile.hotspot
- 10/jdk/ubuntu/Dockerfile.hotspot
- README.md
- build_all.sh
- build_latest.sh
- common_functions.sh
- generate_latest_sums.sh
- generate_manifest_script.sh
- update_multiarch.sh
Modify all scripts to support this.
Add support for version 10.
> New script to build all supported versions. 

- common_functions.sh
- generate_manifest_script.sh
- update_manifest_all.sh
(Complement to build_all.sh).
Move cleanup from generate_manifest_script.sh to update_manifest_all.sh script.
Add a Warning with sleep before pushing to the official repo.
> Add script to push manifest entries for all versions to hub.docker.com

- generate_manifest_script.sh
Need to read the release info from each of the individual tags.
> Fix hotspot tags.

- 10/jdk/alpine/Dockerfile.hotspot.nightly
- 10/jdk/ubuntu/Dockerfile.hotspot.nightly
- 8/jdk/alpine/Dockerfile.hotspot.nightly
- 8/jdk/alpine/Dockerfile.openj9.nightly
- 8/jdk/ubuntu/Dockerfile.hotspot.nightly
- 8/jdk/ubuntu/Dockerfile.openj9.nightly
- 9/jdk/alpine/Dockerfile.hotspot.nightly
- 9/jdk/alpine/Dockerfile.openj9.nightly
- 9/jdk/ubuntu/Dockerfile.hotspot.nightly
- 9/jdk/ubuntu/Dockerfile.openj9.nightly
- build_latest.sh
- common_functions.sh
- generate_latest_sums.sh
- generate_manifest_script.sh
- update_multiarch.sh
Signed-off-by: Ashutosh Mehra <asmehra1@in.ibm.com>
> Update scripts to create Dockerfile and manifest file for nightly builds

- generate_latest_sums.sh
Closes: #18 
Signed-off-by: Ashutosh Mehra <asmehra1@in.ibm.com>
> Update full_version for nightly build to remove date from the end

- 10/jdk/alpine/Dockerfile.hotspot.nightly
- 10/jdk/alpine/Dockerfile.openj9.nightly
- 10/jdk/ubuntu/Dockerfile.openj9.nightly
- generate_latest_sums.sh
- update_multiarch.sh
Add libz support for Alpine Linux
Update to use Alpine 3.7 
Generate nightly builds independent of release builds.
> Fix Alpine nightly builds

- .gitignore
- 10/jdk/alpine/Dockerfile.hotspot
- 10/jdk/alpine/Dockerfile.hotspot.nightly
- 10/jdk/alpine/Dockerfile.openj9.nightly
- 10/jdk/ubuntu/Dockerfile.hotspot
- 10/jdk/ubuntu/Dockerfile.hotspot.nightly
- 10/jdk/ubuntu/Dockerfile.openj9.nightly
- 8/jdk/alpine/Dockerfile.hotspot
- 8/jdk/alpine/Dockerfile.hotspot.nightly
- 8/jdk/alpine/Dockerfile.openj9
- 8/jdk/alpine/Dockerfile.openj9.nightly
- 8/jdk/ubuntu/Dockerfile.hotspot
- 8/jdk/ubuntu/Dockerfile.hotspot.nightly
- 8/jdk/ubuntu/Dockerfile.openj9
- 8/jdk/ubuntu/Dockerfile.openj9.nightly
- 9/jdk/alpine/Dockerfile.hotspot
- 9/jdk/alpine/Dockerfile.hotspot.nightly
- 9/jdk/alpine/Dockerfile.openj9
- 9/jdk/alpine/Dockerfile.openj9.nightly
- 9/jdk/ubuntu/Dockerfile.hotspot
- 9/jdk/ubuntu/Dockerfile.hotspot.nightly
- 9/jdk/ubuntu/Dockerfile.openj9
- 9/jdk/ubuntu/Dockerfile.openj9.nightly
Added JAVA_HOME env property. also re-using JAVA_VERSION to minimise changes and mistakes.
> Added JAVA_HOME env property

- build_all.sh
- common_functions.sh
- hotspot.config
- test_all.sh
- test_multiarch.sh
Add scripts to download test the docker images from hub.docker.com after build-pushing them.
Currently this script does a docker pull and runs a java -version test only.
> Add test scripts

- README.md
- config/README.md
Add a README.md to the config dir.
> Update README.md to match the latest script changes.

- dockerfile_functions.sh
This makes alpine images smaller by removing build/fetch dependencies at each layer. Also optimises installed packages which may improve build times slightly.
> Optimise package managment for alpine-based builds

- common_functions.sh
- dockerfile_functions.sh
This helps to make the Dockerfiles more robust.
> Use github links for download URLs in the Dockerfile

- common_functions.sh
> Really make sure that only 8 and 11 versions are built.

- build_latest.sh
- common_functions.sh
- config/hotspot.config
- config/openj9.config
- config/tags.config
- dockerfile_functions.sh
Will cover slim JRE images in a separate PR.
> Add support for JRE docker images.

- config/slim-java_lib_del.list
> tools.jar should be present for javac to work.

- .travis.yml
- README.md
- linter.sh
> Closes AdoptOpenJDK/openjdk-docker/issues#119 - Add hadolint for linting Dockerfiles

- common_functions.sh
- config/hotspot.config
- config/openj9.config
- config/tags.config
- dockerfile_functions.sh
- update_multiarch.sh
Implements #136 for offering debian in addition to ubuntu and alpine. Motivation can be found in the issue
> Implements debian as an additional docker image for all arches #136

- 11/jre/alpine/Dockerfile.hotspot.releases.full
- dockerfile_functions.sh
Update zlib to 2.11-3 for Alpine Linux builds #147
> Update zlib to 2.11-3

- README.md
Based on a query in slack where user wasn't clear what was being stripped
Signed-off-by: Stewart Addison <sxa@uk.ibm.com>
> Provide link from README to the script that produces slim images

- dockerfile_functions.sh
Also treating this pull request as a bit of a "no op" change to determine whether builds are working correctly.
> Updated mention of which scripts can generate the Dockerfiles.

- README.md
- common_functions.sh
- config/hotspot-official.config
- config/hotspot.config
- config/openj9.config
- config/tags.config
- dockerfile_functions.sh
README.md updates and cleanups.
> Add support for RedHat Regular UBI images.

- build_all.sh
- build_latest.sh
- common_functions.sh
- config/hotspot-official.config
- config/hotspot.config
- config/openj9-official.config
- config/openj9.config
- generate_manifest_script.sh
- test_all.sh
- test_multiarch.sh
- update_manifest_all.sh
> WIP: Add support generating Version 14 images.

- generate_manifest_script.sh
Run through all OSes for manifest generation and not only those on x86_64 arch.
> Generate clefos manifests 

- dockerhub_doc_config_update.sh
Tag generation for updating documentation on DockerHub during releases needs to account for newer OSes that we support
> Fix tag generation for dockerhub release doc updates.

- slim-java.sh
> Update slim script to not call pack200 for version >= 14 as it is now deprecated.

- build_all.sh
Signed-off-by: Stewart Addison <sxa@uk.ibm.com>
> Add timestamps and more verbose messages to each step of the build_all.sh

- dockerhub_doc_config_update.sh
> Fix dockerhub doc tags generated for ubi, ubi-minimal and jre.

- linter.sh
Please see https://github.com/koalaman/shellcheck/issues/1871 for more details
> Fix broken shellcheck download URL.

- Jenkinsfile
Allows us to take advantage of our docker build agents
> add jenkinsfile pipeline

- Jenkinsfile
- build_all.sh
- build_latest.sh
- common_functions.sh
this should significantly speed up the docker builds
> switch arm32 builds to buildx and disable 13 builds

- .gitignore
- config/hotspot-official.config
- config/openj9-official.config
- dockerhub_doc_config_update.sh
fixes the script to generate official docker PR's
> fix official doc generator script

- build_latest.sh
- dockerfile_functions.sh
- dockerhub_doc_config_update.sh
- update_multiarch.sh
See official image [PR](https://github.com/docker-library/official-images/pull/8781) for more details.
> Fix official docker image build failures.

- dockerfile_functions.sh
SCC script is getting copied on windows. This PR makes sure that SCC is generated only on Linux
@dinogun Can i have it reviewed ?
> Copy SCC scripts only on Linux

- build_latest.sh
- update_multiarch.sh
Avoids scc script getting copied to windows directories
@dinogun Can i have it reviewed ?
> Avoid copying scc script to directory on windows

- generate_openj9_scc.sh
As eclipse download and startup taking lot of build time, currently removing the eclipse specific mechanism in generating SCC.
@dinogun Can i please get it reviewed ?
> Removing eclipse specific mechanism due to longer build time issue

- dockerhub_doc_config_update.sh
> Fix unofficial image dockerhub slim tag documentation entries.

- dockerfile_functions.sh
> Install libffi6 on s390x for hotspot on ubuntu 20.04

- build_all.sh
- build_latest.sh
- common_functions.sh
Adding a summary table can give a high level view of the docker image build status (built successfully or failed to build)
NOTE: This PR is still a work in progress, will remove WIP tag after it's complete.
> Added summary table option

- build_latest.sh
@dinogun I have raised this PR to make sure if there are any multiple tags getting passed in the jenkins build. This can make things clear if we need a loop over the tags which are passed (The function is expecting an array but only one tag is passed in the current implementation)
Can I please have it reviewed ? Thanks in advance.
> Adds an echo to check nightly log

- common_functions.sh
> tag_aliases was mistakenly labeled as a local variable.

- build_process.md
- manifest_process.md
Added a higher level explanation of the generation of docker images, Will be parking it as a  Work In Progress item and update the doc with a complete description.
> Adds the build and manifest process doc

- dockerfile_functions.sh
This makes it so that ltsc2016 uses the older Invoke-WebRequest method. This older method is not ideal which is why I keep the other options using curl.exe.
See #472
https://github.com/AdoptOpenJDK/openjdk-docker/pull/472#issuecomment-820198095
> Fix issue with no curl/tar in ltsc2016

- dockerhub_doc_config_update.sh
Used to generate https://github.com/docker-library/official-images/pull/10083
> update official docker generator script

- build_latest.sh
- common_functions.sh
- generate_manifest_script.sh
- update_multiarch.sh
The arches need to be present both in the ${VM}.config file and shasums file.
> Only build images and create manifests for the right arches

- config/tags.config
Added missing tags, related PR #561
@dinogun Updted tags config, which is required PR update
> Update jdk slim tag ids for leap and tumbleweed

- README.md
Updated README.md for UBI as 8.4
> PR #578, update README.md for UBI
